### ISSUE TITLE
SSLHandshakeException on Installation

### ISSUE THREAD

**Issue by maybeec** [coderplus/m2e-connector-for-jaxws-maven-plugin#4]
Accessing the UpdateSite of the plugin results in a SSLHandshakeException:

```
Unable to read repository at http://coderplus.com/m2e-update-sites/jaxws-maven-plugin/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by JacksonFraser** [comment]
Having the same issue for nearly a month. Added the certificate to my cacerts and still have the error.

**Comment by MaksimOrlov** [comment]
Same issue. Does this plugin is still alive??

**Comment by MaksimOrlov** [comment]
@aneesh-joseph

**Comment by cchet** [comment]
Same with me. Any idea how to install this plugin in Red Hat Developer Studio ?

**Comment by maybeec** [comment]
I think it is an issue with the Java version used as the update site is secured by SSL with LetsEncrypt, which has changed/refreshed their root certs. Unfortunately, Java does not seem to have updated to the latest certs so far. However Java10 seem to have some updates regarding this. Maybe by installing Java10, this issue will be resolved. 
However, I think you should consider to make the update site available without SSL as well to overcome such problems in future.

**Comment by Gelunox** [comment]
I don't think it's an issue with java's cert store, curl for windows and firefox also decline the certificate.

firefox message:
> coderplus.com uses an invalid security certificate.
> 
> The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported.
> 
> Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by cchet** [comment]
I have solved it by adding the following to the ini file:

`-Dorg.eclipse.ecf.provider.filetransfer.excludeContributers=org.eclipse.ecf.provider.filetransfer.httpclient4`

and additionally changing the codeplus url from http to https protocol, because DevStudio wasn't capable of reirecting because HTTP-Code 301 was unkown.

I have also tried to add the LetsEncrypt certificates to the java keystore with this script [https://gist.github.com/Firefishy/109b0f1a90156f6c933a50fe40aa777e](install-letsencrypt.sh), but it did not help.

**Comment by Gelunox** [comment]
@cchet doesn't work for me, I've found this "solution" on [stackoverflow](https://stackoverflow.com/a/40668876) as wel, but it has made zero difference for me


> Unable to read repository at https://coderplus.com/m2e-update-sites/jaxws-maven-plugin/content.xml.
> Unable to read repository at https://coderplus.com/m2e-update-sites/jaxws-maven-plugin/content.xml.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Update: a workaround that worked for me:
I installed fiddler, put it to decrypt https traffic and ignore any certificate errors, added the fiddler certificate to the java truststore, loaded eclipse with jvm proxy settings pointed towards fiddler proxy, and installed the plugin.

or, in short, I man in the middle'd myself.

**Comment by aneesh-joseph** [comment]
apologies for the delayed response, you can use this update site instead

https://coderplus.github.io/m2e-connector-for-jaxws-maven-plugin/

**Comment by JSamir** [comment]
Eclipse by default does not use the github update site. Can that somehow be fixed? 

By that i mean that per default eclipse should use the github update site without me changing the link in eclipse settings manually. New users might be confused by this, since this plugin is automatically detected by eclipse but it uses the wrong update site apparently.
